const express = require("express");
const router = express.Router();
const userRouter = require("./src/users");
const utilRouter = require("./src/util");
const eventsRouter = require("./src/events");
const ticketsRouter = require("./src/tickets");
const userInvitesRouter = require("./src/userInvites");
const notificationsRouter = require("./src/notifications");
const stripeRouter = require("./src/stripe");
const countryCurrencyRouter = require("./src/countryCurrency");
const currencyRouter = require("./src/currency");
const paymentMethodsRouter = require("./src/paymentMethods");
const statusRouter = require("./src/status");
const addressesRouter = require("./src/addresses");
const guestlistsRouter = require("./src/guestlists");
const transactionsRouter = require("./src/transactions");

router.use("/", utilRouter);
router.use("/users", userRouter);
router.use("/userInvites", userInvitesRouter);
router.use("/events", eventsRouter);
router.use("/tickets", ticketsRouter);
router.use("/countryCurrency", countryCurrencyRouter);
router.use("/currency", currencyRouter);
router.use("/paymentMethods", paymentMethodsRouter);
router.use("/status", statusRouter);
router.use("/addresses", addressesRouter);
router.use("/notifications", notificationsRouter);
router.use("/stripe", stripeRouter);
router.use("/guestlists", guestlistsRouter);
router.use("/transactions", transactionsRouter);

module.exports = router;
